
brain:
    files:
        aiml:
            files: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/alice2/aiml
            extension: .aiml
            directories: false
        sets:
            files: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/alice2/sets
            extension: .txt
            directories: false
        maps:
            files: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/alice2/maps
            extension: .txt
            directories: false
        denormal: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/alice2/config/denormal.txt
        normal: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/alice2/config/normal.txt
        gender: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/alice2/config/gender.txt
        person: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/alice2/config/person.txt
        person2: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/alice2/config/person2.txt
        predicates: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/alice2/config/predicates.txt
        pronouns: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/alice2/config/pronouns.txt
        properties: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/alice2/config/properties.txt
        triples: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/alice2/config/triples.txt
        preprocessors: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/alice2/config/preprocessors.txt

bot:
    prompt: ">>>"
    default_response: Sorry, I don't have an answer for that!
    exit_response: So long, and thanks for the fish!